# Advanced configuration with platform exclusion and npm publishing
# Place this file in .github/workflows/ in your Rust project

name: Advanced Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v0.1.0'

jobs:
  release:
    uses: xctions/rust-release/.github/workflows/rust-release.yml@v3
    with:
      binary-name: 'my-advanced-tool'
      release-tag: ${{ github.event.inputs.version || github.ref_name }}
      
      # Exclude ARM64 platforms for faster builds
      exclude: 'linux-arm64,windows-arm64,linux-arm64-musl'
      
      # Custom Rust configuration
      rust-version: '1.75.0'
      cargo-args: '--release --locked --no-default-features --features production'
      
      # Release options
      generate-checksums: true
      create-archives: true
      
      # npm publishing with production tag
      enable-npm: true
      npm-package-name: '@myorg/advanced-tool'
      npm-dist-tag: ${{ contains(github.ref_name, 'rc') && 'rc' || contains(github.ref_name, 'beta') && 'beta' || 'latest' }}
      npm-description: 'Advanced development tool with production-ready features'
      
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}