# Basic Rust release example
# Place this file in .github/workflows/ in your Rust project

name: Basic Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: xctions/rust-release/.github/workflows/rust-release.yml@v3
    # Uses default platforms: mac-arm64, linux-x86_64, linux-arm64
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}