# Example with selective platform builds including musl targets
# Place this file in .github/workflows/ in your Rust project

name: Selective Platform Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: xctions/rust-release/.github/workflows/reusable-rust-release.yml@v2
    with:
      binary-name: 'my-app'
      release-tag: ${{ github.ref_name }}
      
      # Build specific platforms by excluding others
      # This builds: linux-x86_64, linux-x86_64-musl, mac-arm64, windows-x86_64
      exclude: 'linux-arm64,linux-arm64-musl,mac-x86_64,windows-arm64'
      
      rust-version: 'stable'
      cargo-args: '--release'
      generate-checksums: true
      create-archives: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}