# Minimal example - builds for all platforms using repository name as binary name
name: Simple Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xctions/rust-release@v1
        with:
          # binary-name is optional - uses repository name by default
          release-tag: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}