# Rust release with npm publishing
# Place this file in .github/workflows/ in your Rust project

name: Release with npm

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: xctions/rust-release/.github/workflows/rust-release.yml@v3
    with:
      # Use custom binary name and enable npm publishing
      binary-name: 'my-cli'
      release-tag: ${{ github.ref_name }}
      
      # Enable npm publishing
      enable-npm: true
      npm-package-name: 'my-cli'
      npm-dist-tag: 'beta'  # Safe deployment strategy
      npm-description: 'My awesome CLI tool built with Rust'
      
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}