name: Rust Build & Release

on:
  workflow_call:
    inputs:
      binary-name:
        description: 'Binary name (defaults to repository name)'
        required: false
        type: string
        default: ''
      platforms:
        description: 'Comma-separated platforms to include'
        required: false
        type: string
        default: 'mac-arm64,linux-x86_64,linux-arm64'
      rust-version:
        description: 'Rust version to use'
        required: false
        type: string
        default: 'stable'
      cargo-args:
        description: 'Additional cargo build arguments'
        required: false
        type: string
        default: '--release'
      generate-checksums:
        description: 'Generate SHA256 checksums'
        required: false
        type: boolean
        default: true
      create-archives:
        description: 'Create tar.gz/zip archives'
        required: false
        type: boolean
        default: true
      # npm publishing options
      enable-npm:
        description: 'Enable npm publishing'
        required: false
        type: boolean
        default: false
      npm-package-name:
        description: 'npm package name (required if enable-npm=true)'
        required: false
        type: string
        default: ''
      npm-dist-tag:
        description: 'npm dist-tag (auto-detected from release tag if not specified)'
        required: false
        type: string
        default: ''
      npm-description:
        description: 'Package description'
        required: false
        type: string
        default: ''
    secrets:
      GITHUB_TOKEN:
        required: true
      NPM_TOKEN:
        required: false
  workflow_dispatch:
    inputs:
      binary-name:
        description: 'Binary name (defaults to repository name)'
        required: false
        type: string
        default: ''
      platforms:
        description: 'Comma-separated platforms to include'
        required: false
        type: string
        default: 'mac-arm64,linux-x86_64,linux-arm64'
      rust-version:
        description: 'Rust version to use'
        required: false
        type: string
        default: 'stable'
      cargo-args:
        description: 'Additional cargo build arguments'
        required: false
        type: string
        default: '--release'
      generate-checksums:
        description: 'Generate SHA256 checksums'
        required: false
        type: boolean
        default: true
      create-archives:
        description: 'Create tar.gz/zip archives'
        required: false
        type: boolean
        default: true
      # npm publishing options
      enable-npm:
        description: 'Enable npm publishing'
        required: false
        type: boolean
        default: false
      npm-package-name:
        description: 'npm package name (required if enable-npm=true)'
        required: false
        type: string
        default: ''
      npm-dist-tag:
        description: 'npm dist-tag (auto-detected from release tag if not specified)'
        required: false
        type: string
        default: ''
      npm-description:
        description: 'Package description'
        required: false
        type: string
        default: ''

env:
  CARGO_TERM_COLOR: always
  # Default platform matrix - simplified to 3 supported platforms
  PLATFORMS: '[
    {"target": "x86_64-unknown-linux-gnu", "os": "ubuntu-latest", "platform": "linux-x86_64"},
    {"target": "aarch64-unknown-linux-gnu", "os": "ubuntu-latest", "platform": "linux-arm64"},
    {"target": "aarch64-apple-darwin", "os": "macos-latest", "platform": "mac-arm64"}
  ]'

jobs:
  prepare:
    name: Prepare Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter-platforms.outputs.platforms }}
      binary-name: ${{ steps.setup.outputs.binary-name }}
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          # Set binary name (auto-detect from repo if not provided)
          BINARY_NAME="${{ inputs.binary-name }}"
          if [[ -z "$BINARY_NAME" ]]; then
            BINARY_NAME="${{ github.event.repository.name }}"
          fi
          
          echo "binary-name=$BINARY_NAME" >> $GITHUB_OUTPUT
          echo "Building binary: $BINARY_NAME"

      - name: Filter platforms
        id: filter-platforms
        shell: bash
        run: |
          ALL_PLATFORMS='${{ env.PLATFORMS }}'
          PLATFORMS_INPUT="${{ inputs.platforms }}"
          
          if [[ -z "$PLATFORMS_INPUT" ]]; then
            # Use default platforms
            echo "platforms=$ALL_PLATFORMS" >> $GITHUB_OUTPUT
          else
            # Filter to include only specified platforms
            INCLUDE_FILTER=""
            IFS=',' read -ra PLATFORM_ARRAY <<< "$PLATFORMS_INPUT"
            for platform in "${PLATFORM_ARRAY[@]}"; do
              platform=$(echo "$platform" | xargs)
              if [[ -n "$INCLUDE_FILTER" ]]; then
                INCLUDE_FILTER="$INCLUDE_FILTER or "
              fi
              INCLUDE_FILTER="$INCLUDE_FILTER.platform == \"$platform\""
            done
            
            FILTERED_PLATFORMS=$(echo "$ALL_PLATFORMS" | jq "[.[] | select($INCLUDE_FILTER)]")
            echo "platforms=$FILTERED_PLATFORMS" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build (${{ matrix.platform }})
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          # Use binary name from prepare job
          BINARY_NAME="${{ needs.prepare.outputs.binary-name }}"
          echo "binary-name=$BINARY_NAME" >> $GITHUB_OUTPUT
          echo "Building binary: $BINARY_NAME for ${{ matrix.platform }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ inputs.rust-version }}
          targets: ${{ matrix.target }}

      - name: Setup cross-compilation
        if: runner.os == 'Linux'
        shell: bash
        run: |
          case "${{ matrix.target }}" in
            aarch64-unknown-linux-gnu)
              sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
              echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              ;;
            x86_64-unknown-linux-musl)
              sudo apt-get update && sudo apt-get install -y musl-tools
              ;;
            aarch64-unknown-linux-musl)
              sudo apt-get update && sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu
              echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              ;;
          esac

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-

      - name: Build binary
        shell: bash
        run: |
          BINARY_NAME="${{ steps.setup.outputs.binary-name }}"
          
          # Build binary (let cargo handle validation and errors)
          cargo build --bin "$BINARY_NAME" --target ${{ matrix.target }} ${{ inputs.cargo-args }}
          
          # No Windows support - all binaries are Unix executables
          BINARY_EXT=""
          
          # Copy to release directory
          mkdir -p release
          SOURCE="target/${{ matrix.target }}/release/${BINARY_NAME}${BINARY_EXT}"
          TARGET="release/${BINARY_NAME}-${{ matrix.platform }}${BINARY_EXT}"
          
          cp "$SOURCE" "$TARGET"
          
          # Set executable permissions
          chmod +x "$TARGET"
          
          echo "Built: $TARGET"

      - name: Create archive
        if: inputs.create-archives
        shell: bash
        run: |
          BINARY_NAME="${{ steps.setup.outputs.binary-name }}"
          PLATFORM="${{ matrix.platform }}"
          TAG="${{ github.ref_name }}"
          
          # All platforms use tar.gz archives
          BINARY_EXT=""
          ARCHIVE_EXT="tar.gz"
          
          BINARY_FILE="${BINARY_NAME}-${PLATFORM}${BINARY_EXT}"
          ARCHIVE_NAME="${BINARY_NAME}-${TAG}-${PLATFORM}"
          
          # Create archive with binary
          mkdir -p "temp/$ARCHIVE_NAME"
          cp "release/$BINARY_FILE" "temp/$ARCHIVE_NAME/"
          
          cd temp
          tar -czf "../release/${ARCHIVE_NAME}.tar.gz" "$ARCHIVE_NAME"
          cd ..
          rm -rf temp
          
          echo "Created: ${ARCHIVE_NAME}.${ARCHIVE_EXT}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.platform }}
          path: release/
          retention-days: 1

  release:
    name: Create GitHub Release
    needs: [prepare, build]
    runs-on: ubuntu-latest
    outputs:
      release-id: ${{ steps.create-release.outputs.id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        shell: bash
        run: |
          mkdir -p release-assets
          find artifacts -type f -exec cp {} release-assets/ \;
          
          echo "Release assets:"
          ls -la release-assets/

      - name: Generate checksums
        if: inputs.generate-checksums
        shell: bash
        run: |
          cd release-assets
          
          if command -v sha256sum >/dev/null; then
            sha256sum * > checksums.txt
          else
            shasum -a 256 * > checksums.txt
          fi
          
          echo "Generated checksums:"
          cat checksums.txt

      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: release-assets/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-publish:
    name: Publish to npm
    if: inputs.enable-npm
    needs: [prepare, build, release]
    runs-on: ubuntu-latest
    steps:
      - name: Validate npm inputs
        shell: bash
        run: |
          if [[ -z "${{ inputs.npm-package-name }}" ]]; then
            echo "Error: npm-package-name is required when enable-npm=true"
            exit 1
          fi
          
          if [[ -z "${{ secrets.NPM_TOKEN }}" ]]; then
            echo "Error: NPM_TOKEN secret is required for npm publishing"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Download release assets
        shell: bash
        run: |
          # Download binaries from GitHub release
          gh release download ${{ github.ref_name }} --dir binaries
          
          echo "Downloaded binaries:"
          ls -la binaries/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create npm package
        shell: bash
        run: |
          BINARY_NAME="${{ needs.prepare.outputs.binary-name }}"
          PACKAGE_NAME="${{ inputs.npm-package-name }}"
          VERSION="${{ github.ref_name }}"
          
          # Remove 'v' prefix from version if present
          VERSION=${VERSION#v}
          
          # Auto-detect npm dist-tag from release tag if not specified
          NPM_DIST_TAG="${{ inputs.npm-dist-tag }}"
          if [[ -z "$NPM_DIST_TAG" ]]; then
            RELEASE_TAG="${{ github.ref_name }}"
            if [[ "$RELEASE_TAG" == *"-alpha"* ]]; then
              NPM_DIST_TAG="alpha"
            elif [[ "$RELEASE_TAG" == *"-beta"* ]]; then
              NPM_DIST_TAG="beta"
            elif [[ "$RELEASE_TAG" == *"-rc"* ]]; then
              NPM_DIST_TAG="rc"
            elif [[ "$RELEASE_TAG" == *"-dev"* ]]; then
              NPM_DIST_TAG="dev"
            else
              NPM_DIST_TAG="latest"
            fi
            echo "Auto-detected npm dist-tag: $NPM_DIST_TAG (from release tag: $RELEASE_TAG)"
          else
            echo "Using specified npm dist-tag: $NPM_DIST_TAG"
          fi
          
          # Create package structure
          mkdir -p npm-package/bin
          
          # Copy binaries for supported platforms
          for platform in linux-x86_64 linux-arm64 mac-arm64; do
            BINARY_FILE="${BINARY_NAME}-${platform}"
            if [[ -f "binaries/$BINARY_FILE" ]]; then
              cp "binaries/$BINARY_FILE" "npm-package/bin/"
            fi
          done
          
          # Create wrapper script
          cat > npm-package/bin/${PACKAGE_NAME} << 'EOF'
          #!/usr/bin/env node
          const { spawn } = require('child_process');
          const path = require('path');
          const os = require('os');
          
          function getBinaryName() {
            const platform = os.platform();
            const arch = os.arch();
            
            let platformName;
            if (platform === 'linux') {
              platformName = arch === 'arm64' ? 'linux-arm64' : 'linux-x86_64';
            } else if (platform === 'darwin') {
              platformName = 'mac-arm64'; // Only ARM64 macOS supported
            } else {
              throw new Error(`Unsupported platform: ${platform}`);
            }
            
            return `BINARY_NAME-${platformName}`;
          }
          
          const binaryName = getBinaryName();
          const binaryPath = path.join(__dirname, binaryName);
          
          const child = spawn(binaryPath, process.argv.slice(2), { stdio: 'inherit' });
          child.on('exit', (code) => process.exit(code));
          EOF
          
          # Replace placeholder in wrapper
          sed -i.bak "s/BINARY_NAME/${BINARY_NAME}/g" npm-package/bin/${PACKAGE_NAME}
          rm npm-package/bin/${PACKAGE_NAME}.bak
          
          chmod +x npm-package/bin/${PACKAGE_NAME}
          
          # Create package.json
          cat > npm-package/package.json << EOF
          {
            "name": "${PACKAGE_NAME}",
            "version": "${VERSION}",
            "description": "${{ inputs.npm-description || format('Command line tool for {0}', needs.prepare.outputs.binary-name) }}",
            "bin": {
              "${PACKAGE_NAME}": "./bin/${PACKAGE_NAME}"
            },
            "files": ["bin/"],
            "keywords": ["cli", "tool", "rust", "binary"],
            "author": "${{ github.repository_owner }}",
            "license": "MIT",
            "homepage": "${{ github.server_url }}/${{ github.repository }}",
            "repository": {
              "type": "git",
              "url": "${{ github.server_url }}/${{ github.repository }}.git"
            },
            "bugs": {
              "url": "${{ github.server_url }}/${{ github.repository }}/issues"
            }
          }
          EOF

      - name: Publish to npm
        shell: bash
        run: |
          cd npm-package
          
          # Use the dist-tag determined in the previous step
          NPM_DIST_TAG="${{ inputs.npm-dist-tag }}"
          if [[ -z "$NPM_DIST_TAG" ]]; then
            RELEASE_TAG="${{ github.ref_name }}"
            if [[ "$RELEASE_TAG" == *"-alpha"* ]]; then
              NPM_DIST_TAG="alpha"
            elif [[ "$RELEASE_TAG" == *"-beta"* ]]; then
              NPM_DIST_TAG="beta"
            elif [[ "$RELEASE_TAG" == *"-rc"* ]]; then
              NPM_DIST_TAG="rc"
            elif [[ "$RELEASE_TAG" == *"-dev"* ]]; then
              NPM_DIST_TAG="dev"
            else
              NPM_DIST_TAG="latest"
            fi
          fi
          
          # Publish with auto-detected or specified dist-tag
          npm publish --tag "$NPM_DIST_TAG"
          
          echo "Published ${{ inputs.npm-package-name }}@$(cat package.json | jq -r .version) with tag: $NPM_DIST_TAG"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}